export const TEMPERATURE_ULTRA_PRECISE_THRESHOLD = 3
export const TEMPERATURE_VERY_PRECISE_THRESHOLD = 5
export const TEMPERATURE_DEGREE_THRESHOLD = 0.5
export const HUMIDITY_THRESHOLD = 1
export const MONOXIDE_PPM_THRESHOLD = 3
